services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    ports: ["8080:8080"]
    depends_on: [db]
  agent:
    build:
      context: .
      dockerfile: services/agent/Dockerfile
    env_file: .env
    depends_on: [api, db, trainer]
  trainer:
    build:
      context: .
      dockerfile: services/trainer/Dockerfile
    env_file: .env
    ports: ["8090:8090"]
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voice
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
